### ISSUE TITLE
Error in build STG

### ISSUE THREAD

**Issue by kotorinxn** [resess/GoalExplorer#14]
I run follow cmd to build STG

`java -jar target/GoalExplorer-1.2.2-SNAPSHOT-jar-with-dependencies.jar ge -s "D:\Android" -o "./out1" --target "api:<android.app.Activity: void onCreate(android.os.Bundle)>" -i "E:\Project\GUIAutoExplore\benchmark\com.fsck.k9_39004.apk"`

but something wrong

```
Exception in thread "main" java.lang.RuntimeException: This operation requires resolving level BODIES but androidx.fragment.app.FragmentActivity is at resolving level SIGNATURES
If you are extending Soot, try to add the following call before calling soot.Main.main(..):
Scene.v().addBasicClass(androidx.fragment.app.FragmentActivity,BODIES);
Otherwise, try whole-program mode (-w).
        at soot.SootClass.checkLevelIgnoreResolving(SootClass.java:210)
        at soot.SootClass.checkLevel(SootClass.java:192)
        at soot.SootMethod.retrieveActiveBody(SootMethod.java:436)
        at android.goal.explorer.analysis.dependency.BranchedFlowAnalysis.<init>(BranchedFlowAnalysis.java:64)
        at android.goal.explorer.builder.ScreenBuilder.collectMenuItemsCallbacks(ScreenBuilder.java:577)
        at android.goal.explorer.builder.ScreenBuilder.parseMenuFromBackstage(ScreenBuilder.java:504)
        at android.goal.explorer.builder.ScreenBuilder.collectOptionsMenuForComponent(ScreenBuilder.java:450)
        at android.goal.explorer.builder.ScreenBuilder.collectMenusForActivity(ScreenBuilder.java:378)
        at android.goal.explorer.builder.ScreenBuilder.collectMenuAndDrawersForInitialScreens(ScreenBuilder.java:342)    
        at android.goal.explorer.builder.ScreenBuilder.collectInitialScreenForActivity(ScreenBuilder.java:281)
        at android.goal.explorer.builder.ScreenBuilder.collectInitialScreens(ScreenBuilder.java:139)
        at android.goal.explorer.builder.ScreenBuilder.constructScreens(ScreenBuilder.java:107)
        at android.goal.explorer.STGExtractor.collectScreens(STGExtractor.java:352)
        at android.goal.explorer.STGExtractor.constructSTG(STGExtractor.java:154)
        at PreAnalysisRunner.run(PreAnalysisRunner.kt:14)
        at Main$Companion.main(Main.kt:21)
        at Main.main(Main.kt)
```

how can I fix this problem?

**Comment by dah-fari7009** [comment]
Hi,

I couldn't reproduce this issue when running the tool on the version of the K9Mail app included in the benchmarks. Could you attach the apk that you used for running the tool and the full execution log? You can use -d option for a more verbose output.

**Comment by kotorinxn** [comment]
I provide the full execution log and K9Mail in attachment
[out.txt](https://github.com/user-attachments/files/17093044/out.txt)
[com.fsck.k9_39004.apk.gz](https://github.com/user-attachments/files/17093039/com.fsck.k9_39004.apk.gz)

**Comment by dah-fari7009** [comment]
Hello,

 The tool does not support applications using the androidx library, which is used by the application based on the logs you provided. Please refer to the README for supported types of applications (under Compatibility: https://github.com/resess/GoalExplorer?tab=readme-ov-file#compatibility).

If you'd like to add support for later Android SDK versions and/or librairies, please feel free to open a PR. Thanks!
